apiVersion:apps/v1
kind:Deployment
metadata
 name:platform-depl
spec
    replicas:1
    selector
        matchLales
            app:microservice
    template
      metadata
       labels
        app:microservice
      spec
        containers
         - name:microservice
           image:ehsanmoosavi/microservice:latest