apiVersion: v1
kind: Service
metadata:
    name: microservicenp-srv
spec:
    type: NodePort
    selector:
        app: microservice
    ports:
        - name: microservice
          protocol: tcp
          port: 80
          targetPort: 80
    
    
